[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
user=orbital

[program:api]
command=gunicorn lib.main:app -c lib/gunicorn_conf.py
autorestart=true
stopasgroup=true
killasgroup=true
startretries=10
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:scheduler]
command=python -m lib.scheduler
autorestart=true
startretries=10
startsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0